services:
  postgres:
    image: postgres:18-alpine
    container_name: ubl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ubl-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ubl-postgres-data:
