services:
  nextjs:
    # build:
    #   context: .
    #   dockerfile: docker/nextjs/Dockerfile.nextjs
    image: ghcr.io/universidade-livre/universidade:nextjs
    init: true
    container_name: ubl-nextjs
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    depends_on:
      nextjs-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    networks:
      - ubl-network
    restart: unless-stopped

  migrate:
    # build:
    #   context: .
    #   dockerfile: docker/nextjs/Dockerfile.migrate
    image: ghcr.io/universidade-livre/universidade:migrate
    init: true
    container_name: ubl-migrate
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ubl-network
    restart: no

  postgres:
    image: postgres:18-alpine
    container_name: ubl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ubl-postgres-data:/var/lib/postgresql/data
    networks:
      - ubl-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ubl-postgres-data:

networks:
  ubl-network:
    external: true
